version: '3.8'

services:
  db:
    image: postgres:15
    container_name: realestate_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: realestate
    ports:
      - "5432:5432"
    volumes:
      - ./sql/DDL.sql:/docker-entrypoint-initdb.d/DDL.sql